### ISSUE TITLE
See Experiment result page

### ISSUE THREAD

**Issue by Alex-Mak-MCW** [CMPUT301W21T23/CMPUT301W21T23-SmartDataBook#9] opened 2021-02-20 02:54 UTC

**Comment by Alex-Mak-MCW** [comment] 2021-02-20 02:56
A page that:

Sees the experiment's result (whether in statistics, graphs, plots, or QR code)

Sees the statistics ( median, mean, standard deviations) of the trials

Sees the experiment's information (owner's name, date of lab created)

**Comment by whqkdhfh13** [comment] 2021-02-20 03:31
Duplicate of #6 , issue closed

**Closed as completed by whqkdhfh13** 2021-02-20 03:31 UTC
